version: '2'

services:
  ecstore:
    image: 'ecstore/docker-ecstore:php72-swooleloader'
    ports:
      - 8001:80
    volumes:
      - .:/data/httpd
    links:
      - mysql
      - redis
    environment:
      - WEBROOT=/data/httpd/public
    networks:
      - bbc

  redis:
    image: redis
    hostname: redis
    ports:
      - "8379:6379"
    volumes:
      - ./storage/redis:/data
    networks:
      - bbc

  mysql:
    image: mysql:5.6
    hostname: mysql
    ports:
      - "8306:3306"
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - bbc

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8004:80"
    links:
      - mysql
    environment:
      - PMA_HOST=mysql
    networks:
      - bbc

networks:
  bbc:
    driver: bridge
